### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by eletricacess** [heyvaldemar/nextcloud-traefik-letsencrypt-docker-compose#5]
lab01@server:~/nextcloud-traefik-letsencrypt-docker-compose$ docker-compose -f nextcloud-traefik-letsencrypt-docker-compose.yml -p nextcloud up -d

ERROR: Invalid interpolation format for "command" option in service "backups": "sh -c 'sleep $BACKUP_INIT_SLEEP && while true; do
  pg_dump -h postgres -p 5432 -d $NEXTCLOUD_DB_NAME -U $NEXTCLOUD_DB_USER | gzip > $POSTGRES_BACKUPS_PATH/$POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz &&
  tar -zcpf $DATA_BACKUPS_PATH/$DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $DATA_PATH &&
  find $POSTGRES_BACKUPS_PATH -type f -mtime +$POSTGRES_BACKUP_PRUNE_DAYS | xargs rm -f &&
  find $DATA_BACKUPS_PATH -type f -mtime +$DATA_BACKUP_PRUNE_DAYS | xargs rm -f;
  sleep $BACKUP_INTERVAL; done'"

**Comment by heyvaldemar** [comment]
hey @eletricacess, just a heads-up that you're using `docker-compose` instead of `docker compose` as mentioned in my guide.

The hyphenated command `docker-compose` is deprecated since Docker introduced Compose V2 in 2020, which integrates more seamlessly into the Docker CLI with improved functionality and ongoing feature development. Since July 2023, Docker has stopped updating Compose V1, and it is no longer available in new Docker Desktop releases.

Transitioning to `docker compose` is advisable to leverage the improved build performance and new features like native BuildKit support, and it's also the default in Docker Desktop settings now. This change ensures your setup remains up-to-date and functional in future Docker implementations.

Also, if you're interested in discussing more about DevOps or have more questions, feel free to join my DevOps community on Discord [here](https://discord.gg/AJQGCCBcqf). It’s a great place to share, learn, and collaborate with others in the field.
